"use client";

import { FormEvent, useState } from "react";

type Scope = { board_id: string; class_id: string; subject_id: string };
type Version = { id: string; version_no: number; status: string; expected_chunk_count: number; embedded_chunk_count: number; expected_question_count: number; embedded_question_count: number };
type Detail = { chunks: { id: string; chapter_id: string; topic_no: string; embedding_status: string }[]; questions: { id: string; chunk_id: string; question_text: string; embedding_status: string }[]; visuals: { id: string; visual_id: string; title: string; description: string; review_status: string; display_policy: string }[]; audits: { id: string; created_at: string; action: string }[] };
type Job = { id: string; job_type: string; status: string; stage: string | null; progress: number; attempt_count: number; max_attempts: number; error_code: string | null };

async function csrf() { const response = await fetch("/api/auth/csrf", { credentials: "same-origin" }); return (await response.json()).csrfToken as string; }

export default function RagAdminClient() {
  const [scope, setScope] = useState<Scope>({ board_id: "", class_id: "", subject_id: "" });
  const [versions, setVersions] = useState<Version[]>([]); const [jobs, setJobs] = useState<Job[]>([]);
  const [selected, setSelected] = useState<string | null>(null); const [details, setDetails] = useState<Detail | null>(null);
  const [status, setStatus] = useState("Select a scope to inspect local corpus versions."); const [busy, setBusy] = useState(false);
  const [question, setQuestion] = useState({ chunk_id: "", id: "", text: "" });
  const [visual, setVisual] = useState({ id: "", title: "", description: "", review_status: "pending", display_policy: "never" });
  const [qaQuestion, setQaQuestion] = useState("");

  async function request(operation: string, corpusVersionId?: string, extra: Record<string, string> = {}) {
    setBusy(true); setStatus("Working…");
    try {
      const response = await fetch("/api/admin/rag", { method: "POST", credentials: "same-origin", headers: { "Content-Type": "application/json", "X-CSRF-Token": await csrf() }, body: JSON.stringify({ operation, ...scope, corpus_version_id: corpusVersionId, ...extra }) });
      const body = await response.json(); if (!response.ok) throw new Error(body.message || "Request rejected");
      return body.data;
    } catch (error) { setStatus(error instanceof Error ? error.message : "Request failed"); return null; } finally { setBusy(false); }
  }
  async function refresh() { const result = await request("overview"); if (result) { setVersions(result.versions || []); setJobs(result.jobs || []); setStatus("Corpus versions and durable jobs loaded."); } }
  async function inspect(versionId: string) { const result = await request("inspect_version", versionId); if (result) { setSelected(versionId); setDetails(result); setQuestion((v) => ({ ...v, chunk_id: result.chunks[0]?.id || "" })); setStatus("Version inspection loaded."); } }
  async function mutate(operation: string, extra: Record<string, string> = {}) { if (!selected) return; const result = await request(operation, selected, extra); if (result) { await refresh(); await inspect(selected); setStatus("Change saved; targeted local embedding work was queued where required."); } }

  return <div className="max-w-6xl p-8">
    <h1 className="text-3xl font-bold">Local RAG QA</h1><p className="mt-2 text-sm">Local-admin-only. Image previews stream through the protected server proxy; storage references never appear here.</p>
    <form className="mt-6 grid grid-cols-1 gap-3 md:grid-cols-4" onSubmit={(event: FormEvent) => { event.preventDefault(); void refresh(); }}>
      {(["board_id", "class_id", "subject_id"] as const).map((field) => <label key={field} className="text-sm">{field}<input required value={scope[field]} onChange={(event) => setScope({ ...scope, [field]: event.target.value })} className="mt-1 w-full rounded border p-2 text-black" /></label>)}
      <button disabled={busy} className="self-end rounded bg-blue-700 p-2 text-white">Load local QA</button>
    </form><p role="status" className="mt-3 text-sm">{status}</p>
    <section className="mt-6"><h2 className="text-xl font-semibold">Corpus versions</h2><div className="mt-2 space-y-2">{versions.map((v) => <div key={v.id} className="rounded border p-3"><div>Version {v.version_no} · {v.status} — chunks {v.embedded_chunk_count}/{v.expected_chunk_count}, questions {v.embedded_question_count}/{v.expected_question_count}</div><div className="mt-2 flex gap-2"><button disabled={busy} onClick={() => void inspect(v.id)} className="rounded border px-2 py-1">Inspect</button>{v.status === "active" && <button disabled={busy} onClick={() => void request("create_draft", v.id).then(refresh)} className="rounded border px-2 py-1">Create draft</button>}{v.status === "qa_ready" && <><button disabled={busy} onClick={() => void request("approve_qa", v.id).then(refresh)} className="rounded border px-2 py-1">Approve QA</button><button disabled={busy} onClick={() => void request("activate", v.id).then(refresh)} className="rounded border px-2 py-1">Activate</button></>}{v.status === "superseded" && <button disabled={busy} onClick={() => void request("rollback", v.id).then(refresh)} className="rounded border px-2 py-1">Rollback</button>}</div></div>)}</div></section>
    <section className="mt-6"><h2 className="text-xl font-semibold">Durable jobs</h2><ul className="mt-2 text-sm">{jobs.map((job) => <li key={job.id}>{job.job_type}: {job.status} / {job.stage || "pending"} / {job.progress}% / attempts {job.attempt_count}/{job.max_attempts}{job.error_code ? ` / ${job.error_code}` : ""}</li>)}</ul></section>
    {selected && details && <section className="mt-8 space-y-6"><h2 className="text-xl font-semibold">Version inspection</h2><div><h3 className="font-medium">Chunks</h3><ul className="text-sm">{details.chunks.map((chunk) => <li key={chunk.id}>{chunk.chapter_id} · {chunk.topic_no} · {chunk.embedding_status}</li>)}</ul></div>
      <form className="space-y-2 rounded border p-3" onSubmit={(event) => { event.preventDefault(); void mutate(question.id ? "edit_question" : "add_question", question.id ? { question_id: question.id, question_text: question.text } : { chunk_id: question.chunk_id, question_text: question.text }); setQuestion((v) => ({ ...v, id: "", text: "" })); }}><h3 className="font-medium">Expected question</h3><select value={question.chunk_id} onChange={(event) => setQuestion({ ...question, chunk_id: event.target.value })} className="rounded border p-2">{details.chunks.map((chunk) => <option key={chunk.id} value={chunk.id}>{chunk.chapter_id} · {chunk.topic_no}</option>)}</select><input required value={question.text} onChange={(event) => setQuestion({ ...question, text: event.target.value })} className="ml-2 rounded border p-2 text-black" /><button disabled={busy} className="ml-2 rounded border px-2 py-1">{question.id ? "Save" : "Add"}</button></form>
      <ul className="text-sm">{details.questions.map((item) => <li key={item.id}>{item.question_text} · {item.embedding_status}<button className="ml-2 underline" onClick={() => setQuestion({ chunk_id: item.chunk_id, id: item.id, text: item.question_text })}>Edit</button><button className="ml-2 underline" onClick={() => void mutate("delete_question", { question_id: item.id })}>Delete</button></li>)}</ul>
      <form className="space-y-2 rounded border p-3" onSubmit={(event) => { event.preventDefault(); void mutate("edit_visual", visual); }}><h3 className="font-medium">Visual metadata</h3><select required value={visual.id} onChange={(event) => { const item = details.visuals.find((v) => v.id === event.target.value); if (item) setVisual(item); }} className="rounded border p-2"><option value="">Select a visual</option>{details.visuals.map((item) => <option key={item.id} value={item.id}>{item.visual_id}</option>)}</select><input required placeholder="Title" value={visual.title} onChange={(event) => setVisual({ ...visual, title: event.target.value })} className="ml-2 rounded border p-2 text-black" /><textarea required placeholder="Description" value={visual.description} onChange={(event) => setVisual({ ...visual, description: event.target.value })} className="ml-2 rounded border p-2 align-middle text-black" /><select value={visual.review_status} onChange={(event) => setVisual({ ...visual, review_status: event.target.value })} className="ml-2 rounded border p-2"><option>pending</option><option>approved</option><option>rejected</option></select><select value={visual.display_policy} onChange={(event) => setVisual({ ...visual, display_policy: event.target.value })} className="ml-2 rounded border p-2"><option>never</option><option>always</option><option>llm_decide</option></select><button disabled={busy || !visual.id} className="ml-2 rounded border px-2 py-1">Save visual</button></form>
      <ul className="text-sm">{details.visuals.map((item) => <li key={item.id}>{item.visual_id} · {item.review_status} · {item.display_policy}<a className="ml-2 underline" target="_blank" rel="noreferrer" href={`/api/admin/rag/visual/${encodeURIComponent(item.id)}?board_id=${encodeURIComponent(scope.board_id)}&class_id=${encodeURIComponent(scope.class_id)}&subject_id=${encodeURIComponent(scope.subject_id)}&corpus_version_id=${encodeURIComponent(selected)}`}>Preview</a></li>)}</ul>
      <form onSubmit={(event) => { event.preventDefault(); void request("qa_search", selected, { question: qaQuestion }).then((result) => result && setStatus(`QA search: ${result.strength}; ${result.reason}; ${result.results.length} result(s).`)); }}><input required value={qaQuestion} onChange={(event) => setQaQuestion(event.target.value)} placeholder="Named-version QA question" className="rounded border p-2 text-black" /><button disabled={busy} className="ml-2 rounded border px-2 py-1">Run QA search</button></form><div><h3 className="font-medium">Audit records</h3><ul className="text-sm">{details.audits.map((audit) => <li key={audit.id}>{audit.created_at}: {audit.action}</li>)}</ul></div></section>}
  </div>;
}
