"use client";

import { useEffect, useState } from "react";

type Row = Record<string, unknown>;
type Dashboard = { summary: { job_count: number }; jobs: Row[]; rag: Row; answers: Row; retrieval: { numerator: number; denominator: number; rate: number }; providers: Row[]; quota: { blocks: number }; test_generation: { failures: number }; recent_failures: Row[] };
type Audit = { id: string; action: string; target_type: string; target_id: string; created_at: string };
const value = (item: unknown) => typeof item === "number" ? item : 0;

export default function OperationsDashboard() {
  const [window, setWindow] = useState("24h"); const [data, setData] = useState<Dashboard | null>(null); const [error, setError] = useState("");
  const [audits, setAudits] = useState<Audit[]>([]); const [auditError, setAuditError] = useState(""); const [action, setAction] = useState(""); const [targetType, setTargetType] = useState(""); const [targetId, setTargetId] = useState(""); const [errorCode, setErrorCode] = useState(""); const [cursor, setCursor] = useState<string | null>(null); const [pageStart, setPageStart] = useState<string | null>(null); const [history, setHistory] = useState<Array<string | null>>([]);
  useEffect(() => { setData(null); setError(""); fetch(`/api/admin/operations/dashboard?window=${window}`, { cache: "no-store" }).then(async (response) => response.ok ? setData(await response.json()) : setError("Operational data is unavailable.")).catch(() => setError("Operational data is unavailable.")); }, [window]);
  const loadAudits = (next: string | null = null) => { setAuditError(""); const params = new URLSearchParams({ window, limit: "50" }); if (action) params.set("action", action); if (targetType) params.set("target_type", targetType); if (targetId) params.set("target_id", targetId); if (errorCode) params.set("error_code", errorCode); if (next) params.set("cursor", next); fetch(`/api/admin/operations/audits?${params}`, { cache: "no-store" }).then(async (response) => { if (!response.ok) throw new Error(); const payload = await response.json(); setAudits(payload.items); setCursor(payload.next_cursor); }).catch(() => setAuditError("Audit history is unavailable.")); };
  // Filters are submitted explicitly; including the render-local loader would refetch on each render.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(() => { setHistory([]); setPageStart(null); loadAudits(); }, [window]);
  const cards = data ? [["Jobs", data.summary.job_count], ["Retrieval empty", `${value(data.retrieval.numerator)}/${value(data.retrieval.denominator)} (${(value(data.retrieval.rate) * 100).toFixed(1)}%)`], ["Quota blocks", data.quota.blocks], ["General AI fallbacks", value(data.answers.general_fallbacks)], ["Approved-bank hits", value(data.answers.approved_bank_hits)], ["Pending candidates", value(data.answers.pending_candidates)], ["Test-generation failures", data.test_generation.failures]] : [];
  return <main className="max-w-6xl p-8"><h1 className="text-3xl font-bold">Operations dashboard</h1><label className="mt-4 block">Time window <select aria-label="Time window" className="ml-2 border p-2" value={window} onChange={(event) => setWindow(event.target.value)}><option>24h</option><option>7d</option><option>30d</option></select></label>{error && <p role="alert" className="mt-4">{error}</p>}{!data && !error && <p className="mt-4">Loading persisted operational data…</p>}{data && <><p className="mt-2 text-sm text-gray-600">All values are persisted data for this window; Multiple Ask rows follow their retention policy.</p><section className="mt-6 grid gap-4 md:grid-cols-3">{cards.map(([label, count]) => <div className="rounded border bg-white p-4" key={String(label)}><p className="text-sm text-gray-600">{label}</p><p className="text-xl font-bold">{String(count)}</p></div>)}</section><Table title="Jobs" rows={data.jobs}/><Table title="RAG" rows={Object.entries(data.rag).map(([metric, count]) => ({ metric, count }))}/><Table title="Answers" rows={Object.entries(data.answers).map(([metric, count]) => ({ metric, count }))}/><Table title="Provider errors" rows={data.providers}/><Table title="Recent sanitized failures" rows={data.recent_failures}/></>}<section className="mt-8"><h2 className="text-xl font-semibold">Audit history</h2><form className="mt-2 grid gap-2 md:grid-cols-5" onSubmit={(event) => { event.preventDefault(); setHistory([]); setPageStart(null); loadAudits(); }}><input aria-label="Audit action" className="border p-2" placeholder="Action" value={action} onChange={(event) => setAction(event.target.value)} /><input aria-label="Audit target type" className="border p-2" placeholder="Target type" value={targetType} onChange={(event) => setTargetType(event.target.value)} /><input aria-label="Audit target ID" className="border p-2" placeholder="Target ID" value={targetId} onChange={(event) => setTargetId(event.target.value)} /><input aria-label="Audit error code" className="border p-2" placeholder="Error code" value={errorCode} onChange={(event) => setErrorCode(event.target.value)} /><button className="rounded bg-blue-700 p-2 text-white" type="submit">Search</button></form>{auditError && <p role="alert">{auditError}</p>}{!auditError && <Table title="" rows={audits as unknown as Row[]}/>}<div className="mt-2 flex gap-2"><button disabled={!history.length} className="border p-2 disabled:opacity-50" onClick={() => { const prior = history.at(-1) ?? null; setHistory((items) => items.slice(0, -1)); setPageStart(prior); loadAudits(prior); }}>Previous</button><button disabled={!cursor} className="border p-2 disabled:opacity-50" onClick={() => { if (cursor) { setHistory((items) => [...items, pageStart]); setPageStart(cursor); loadAudits(cursor); } }}>Next</button></div></section></main>;
}

function Table({ title, rows }: { title: string; rows: Row[] }) { const keys = rows[0] ? Object.keys(rows[0]) : []; return <section className={title ? "mt-8" : "mt-2"}>{title && <h2 className="text-xl font-semibold">{title}</h2>}{!rows.length ? <p className="mt-2 text-sm">No retained records in this period.</p> : <div className="overflow-auto"><table className="mt-2 w-full border text-sm"><thead><tr>{keys.map((key) => <th className="border p-2 text-left" key={key}>{key.replaceAll("_", " ")}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={index}>{keys.map((key) => <td className="border p-2" key={key}>{String(row[key] ?? "—")}</td>)}</tr>)}</tbody></table></div>}</section>; }
